---
- name: "Update apt-cache (Debian)"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 43200
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: "Install python-setuptools"
  ansible.builtin.package:
    name: ['python3-setuptools']
    state: present

- name: "Install requirements"
  ansible.builtin.package:
    name: "{{ burpui_py3_packages| join(',') }}"
    state: present

- name: "Delete cryptography to reinstall it with Pip"
  ansible.builtin.package:
    name: "{{ burpui_system_absent }}"
    state: absent
